name: convenient_test_manager_dart
description: Write and debug tests easily, with full action history, time travel, screenshots, rapid re-execution, video records, interactivity, isolation and more
version: 1.2.1
repository: https://github.com/fzyzcjy/flutter_convenient_test

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  args: ^2.3.1
  collection: ^1.15.0
  convenient_test_common_dart: ^1.0.0
  fixnum: ^1.0.0
  freezed_annotation: ^2.0.3
  get_it: ^7.0.0
  grpc: ^3.0.0
  intl: ^0.17.0
  meta: ^1.3.0
  mobx: ^2.0.6
  recase: ^4.0.0
  test_api: ^0.4.2
  vm_service: ">=8.0.0 <10.0.0"

dependency_overrides:
  convenient_test_common_dart:
    path: ../convenient_test_common_dart
  grpc:
    git:
      url: https://github.com/fzyzcjy/grpc-dart # #3761

dev_dependencies:
  build_runner: ^2.1.2
  dart_code_metrics: ^4.15.0
  freezed: ^2.0.3
  json_serializable: ^6.2.0
  lint: ^1.8.2
  mobx_codegen: ^2.0.6
  test: ^1.20.1
