name: convenient_test_manager_dart
description: Write and debug tests easily, with full action history, time travel, screenshots, rapid re-execution, video records, interactivity, isolation and more
version: 1.5.5
repository: https://github.com/fzyzcjy/flutter_convenient_test

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  args: ^2.7.0
  collection: '>=1.19.0 <1.20.0'
  convenient_test_common_dart: '>=1.5.0 <1.6.0'
  fixnum: ^1.1.1
  freezed_annotation: ^3.1.0
  get_it: '>=8.0.0 <9.0.0'
  grpc: ^5.0.0
  intl: '>=0.19.0 <0.21.0'
  json_annotation: ^4.9.0
  meta: ^1.17.0
  mobx: ^2.5.0
  protobuf: '>=5.0.0 <7.0.0'
  recase: ^4.1.0
  synchronized: '>=3.0.0 <4.0.0'
  test_api: '>=0.7.7 <0.8.0'
  vm_service: '>=14.0.0 <15.0.0'

dependency_overrides:
  analyzer: '>=8.0.0 <10.0.0'
  convenient_test_common_dart:
    path: ../convenient_test_common_dart

dev_dependencies:
  build_runner: '>=2.10.0 <2.11.0'
  freezed: ^3.2.3
  json_serializable: '>=6.9.1 <7.0.0'
  lint: '>=1.8.2 <3.0.0'
  mobx_codegen: ^2.7.4
  test: ^1.28.0
