name: convenient_test_dev
description: Write and debug tests easily, with full action history, time travel, screenshots, rapid re-execution, video records, interactivity, isolation and more
version: 1.5.4
repository: https://github.com/fzyzcjy/flutter_convenient_test

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.1"

dependencies:
  collection: '>=1.19.0 <1.20.0'
  convenient_test: ^1.0.0
  convenient_test_common: ^1.0.0
  convenient_test_common_dart: ^1.0.0
  fixnum: ^1.1.1
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  freezed_annotation: ^3.0.0
  get_it: '>=7.0.0 <9.0.0'
  grpc: ^4.0.4
  image: ^4.5.4
  integration_test:
    sdk: flutter
  intl: '>=0.19.0 <0.21.0'
  json_annotation: ^4.9.0
  lint: ">=1.8.2 <3.0.0"
  matcher: ^0.12.17
  meta: ^1.16.0
  path: ^1.9.1
  path_provider: ^2.1.5
  recase: ^4.1.0
  test_api: '>=0.5.1 <0.8.0'
  tuple: ^2.0.2
  web_socket_channel: ^3.0.3

dev_dependencies:
  build_runner: '>=2.3.0 <2.5.0'
  freezed: ^3.0.6
  json_serializable: '>=6.9.1 <7.0.0'

# dependency_overrides:
#   convenient_test:
#     path: ../convenient_test
#   convenient_test_common:
#     path: ../convenient_test_common
#   convenient_test_common_dart:
#     path: ../convenient_test_common_dart

dependency_overrides:
  convenient_test_common:
    path: ../convenient_test_common
  convenient_test_common_dart:
    path: ../convenient_test_common_dart
