name: convenient_test_dev
description: Write and debug tests easily, with full action history, time travel, screenshots, rapid re-execution, video records, interactivity, isolation and more
version: 1.2.1
repository: https://github.com/fzyzcjy/flutter_convenient_test

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.15.0
  convenient_test: ^1.0.0
  convenient_test_common: ^1.0.0
  convenient_test_common_dart: ^1.0.0
  fixnum: ^1.0.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  freezed_annotation: ^2.0.0
  get_it: ^7.0.0
  grpc: ^3.0.0
  image: ^3.1.3
  integration_test:
    sdk: flutter
  intl: ^0.17.0
  json_annotation: ^4.4.0
  lint: ^1.8.2
  meta: ^1.3.0
  path: ^1.8.0
  path_provider: ^2.0.9
  recase: ^4.0.0
  test_api: ^0.4.2
  web_socket_channel: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.2
  dart_code_metrics: ^4.15.0
  freezed: ^2.0.0
  json_serializable: ^6.1.5
# dependency_overrides:
#   convenient_test:
#     path: ../convenient_test
#   convenient_test_common:
#     path: ../convenient_test_common
#   convenient_test_common_dart:
#     path: ../convenient_test_common_dart
