name: convenient_test
description: Write and debug tests easily, with full action history, time travel, screenshots, rapid re-execution, video records, interactivity, isolation and more
version: 1.2.1
repository: https://github.com/fzyzcjy/flutter_convenient_test

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^4.15.0
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
