name: convenient_test
description: Write and debug tests easily, with full action history, time travel, screenshots, rapid re-execution, video records, interactivity, isolation and more
version: 1.5.4
repository: https://github.com/fzyzcjy/flutter_convenient_test

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  collection: '>=1.19.0 <1.20.0'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ">=2.8.0 <3.0.0"