name: convenient_test_common
description: Write and debug tests easily, with full action history, time travel, screenshots, rapid re-execution, video records, interactivity, isolation and more
version: 1.6.0
repository: https://github.com/fzyzcjy/flutter_convenient_test
environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"
dependencies:
  collection: '>=1.19.0 <1.20.0'
  convenient_test_common_dart: '>=1.5.0 <1.6.0'
  fixnum: ^1.1.1
  flutter:
    sdk: flutter
  grpc: ^5.1.0
  mobx: ^2.5.0
  protobuf: '>=6.0.0 <7.0.0'
  quiver: ^3.2.2
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ">=2.8.0 <3.0.0"

dependency_overrides:
  convenient_test_common_dart:
    path: ../convenient_test_common_dart